describe("smoke", function()
    it("loads al.state without error", function()
        assert.has_no.errors(function()
            require("al.state")
        end)
    end)

    it("loads al.cmd without error", function()
        assert.has_no.errors(function()
            require("al.cmd")
        end)
    end)

    it("loads al.ui without error", function()
        assert.has_no.errors(function()
            require("al.ui")
        end)
    end)
end)
